package com.anypresence.anypresence_inc.examplea.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table APOBJECTS_APCACHED_REQUESTS.
 */
public class APObjectsAPCachedRequests {

	private Long apObjectId;
	private Long apCachedRequestId;

	// KEEP FIELDS - put your custom fields here
	// KEEP FIELDS END

	public APObjectsAPCachedRequests() {
	}

	public APObjectsAPCachedRequests(Long apObjectId, Long apCachedRequestId) {
		this.apObjectId = apObjectId;
		this.apCachedRequestId = apCachedRequestId;
	}

	public Long getApObjectId() {
		return apObjectId;
	}

	public void setApObjectId(Long apObjectId) {
		this.apObjectId = apObjectId;
	}

	public Long getApCachedRequestId() {
		return apCachedRequestId;
	}

	public void setApCachedRequestId(Long apCachedRequestId) {
		this.apCachedRequestId = apCachedRequestId;
	}

	// KEEP METHODS - put your custom methods here
	// KEEP METHODS END

}
