package com.anypresence.sdk.cache.greendao;

//
//  GreenDAOSessionHelper.java
//  
//
//  Generated by AnyPresence, Inc on 2014-12-19
//  Copyright (c) 2014. All rights reserved.
//

import de.greenrobot.dao.query.*;
import de.greenrobot.dao.*;
import com.anypresence.sdk.acl.*;
import com.anypresence.sdk.callbacks.*;
import com.anypresence.sdk.query.*;
import com.anypresence.sdk.APSDKSetup;
import java.lang.reflect.*;
import com.anypresence.sdk.cache.*;
import com.anypresence.sdk.cache.internal.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.anypresence.sdk.cache.internal.*;
import com.anypresence.sdk.cache.internal.APObjectsAPCachedRequests;
import com.anypresence.anypresence_inc.examplea.dao.DaoMaster;
import com.anypresence.anypresence_inc.examplea.dao.DaoSession;
import android.database.sqlite.SQLiteDatabase;
import com.anypresence.sdk.examplea.models.*;
import com.anypresence.rails_droid.*;
import com.anypresence.sdk.config.Config;

import static com.anypresence.sdk.APSDKSetup.DEBUG_MODE;

import java.util.*;

class GreenDAOSessionHelper implements IDAOSession {
	private DaoSession session;

	public GreenDAOSessionHelper(DaoSession session) {
		this.session = session;
	}

	public Object getRaw() {
		return this.session;
	}

	public void runInTx(Runnable r) {
		this.session.runInTx(r);
	}
}
